### PR TITLE
Fix settings

### LINKED ISSUE #64: Add setting sub section titles to top toolbar
e.g. Database.

### LINKED ISSUE #76: Group settings into separate section screens

### LINKED ISSUE #112: Add link to docs in about page

### LINKED ISSUE #120: Move About to bottom of Settings

### PR DESCRIPTION
**Pull request by kamathprasad9**
Group setting categories
Add toolbars to individual category's screen
Move about section to settings

Closes #64
Closes #76 
Closes #120 
Closes #112

### CODE REVIEW

**Comment by kamathprasad9** [comment]
For some reason, permissions are not being requested to the user in StorageDefinerFragment, causing the definer to be closed unexpectedly. Any help would be appreciated!

**Comment by chaneylc** [comment]
targeting 34 means we don't need to request read/write storage so the permissions logic was skipping the document tree call

**Comment by trife** [comment]
- [ ] Resolve conflicts
- [ ] [Add search widget](https://github.com/ByteHamster/SearchPreference)
- [ ] Move database settings to section of Storage instead of separate panel
- [ ] Remove layout section and add as subsection in Collection
- [ ] Create new section ("Unique") and move Unique required and Unique options to it
- [ ] Hide Unique Options if Unique required is not enabled
- [ ] Change text to "Require sample IDs to be unique"
- [ ] There's a strange screen reloading animation that happens when going to back to the main settings page.

**Comment by trife** [comment]
- [ ] Bottom bar navigation no longer works when navigating to settings
- [ ] Search widget hides bottom toolbar
- [ ] No way to exit search widget when it's active- probably should add "Settings" to main settings toolbar with back button
- [ ] Modify storage definer to use the same one as field book (without the ability to skip or migrate)

**Review by trife — APPROVED** [review]

**Pull request merged**
